[package]
name = "Examples"
version = "1.0.0"
authors = []

[addresses]
# `aptos move compile --save-metadata` refers the following addresses as the module owner.
MoonCoin = "ad3962458c2b2872fae70cc4dd48466815f21037e7217124ecd2b0da3896e1ca"
#FACoin = "ad3962458c2b2872fae70cc4dd48466815f21037e7217124ecd2b0da3896e1ca"
FACoin = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
