[package]
name = "Tutorial"
version = "1.0.0"
authors = []

[addresses]
MoonCoin = "ad3962458c2b2872fae70cc4dd48466815f21037e7217124ecd2b0da3896e1ca"
FACoin = "0xa816be8abfbcb2c61fd5032715a8ff4155fd19ad67b379c4482bf0a10d320ed9"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
